name: Python unit tests

on: pull_request

jobs:
  run-tests:
    runs-on:
      - ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Setup Python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Install project dependencies
        run: poetry install --no-interaction
      - name: Run tests
        run: poetry run pytest tests
